spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mtsmadb
    username: postgres
    password: mechack200
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
  expiration: 86400000
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
#liquibase:
#  change-log: classpath:db/db.changelog/db.changelog-master.xml
#  enabled: true
#  default-schema: public
#  drop-first: false
#  contexts: development

#logging:
#  level:
#    liquibase: INFO

