#spring.application.name=multi-tenant-school
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=multischool455@gmail.com
#spring.mail.password=psptnfacmitlempz
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

spring.application.name=multi-tenant-school

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=multischool455@gmail.com
spring.mail.password=psptnfacmitlempz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.debug=true


# multi media type configuration
spring.servlet.multipart.enabled=true
upload.directory=${user.home}/Desktop/uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# Frontend URL where users verify email
app.frontend.url=https://mtsma.com



